export * from './Banner/Banner';
export * from './Navbar/Navbar';
export * from './PresentCard/PresentCard';
export * from './StarsBg/StarsBg';
export * from './ProjectCard/ProjectCard';
export * from './About/About';
export * from './Skills/Skill';
export * from './SkillCard/SkillCard';
export * from './LanguageBtn/LanguageBtn';